### PR TITLE
Support yum-based platforms

### PR DESCRIPTION
**Pull request by kpruden**

### CODE REVIEW

**Comment by leonmax** [comment]
Thanks! @kpruden

**Comment by kpruden** [comment]
No problem @leonmax, thanks for writing the module in the first place.

The updates haven't appeared yet on puppet forge.  It looks like there's an extra step you need to take to make it aware of the update: http://docs.puppetlabs.com/puppet/3/reference/modules_publishing.html#release-a-new-version.

When you have a change, can you upload the update, so I can stop referencing my personal fork :)

Thanks!

**Comment by leonmax** [comment]
Hey, @kpruden,
sorry about the wait, but I've updated the modules on Puppet Forge

**Comment by kpruden** [comment]
Great, thanks!

**Pull request merged**
